version: "3.9"

services:
  db:
    build:
      context: ./MySQL
      args:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=wordpress
    volumes:
      - db_data:/var/lib/mysql
    restart: always
      
  wordpress:
    depends_on:
      - db
    build: 
      context: ./Wordpress
      args:
        - WORDPRESS_DB_HOST=db:3306
        - WORDPRESS_DB_USER=wordpress
        - WORDPRESS_DB_PASSWORD=wordpress
        - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    ports:
      - "8000:80"

volumes:
  db_data: {}
  wordpress_data: {}